In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Crime_Data .csv.csv")

In [ ]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,8/25/2007 9:22,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007,8/17/2015 15:03,NaN,NaN,NaN
1,25953,JE240540,5/24/2021 15:06,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,11/18/2023 15:39,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,6/26/2021 9:24,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021,11/18/2023 15:39,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,11/9/2023 7:30,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,47.0,5.0,5,1162518.0,1925906.0,2023,11/18/2023 15:39,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,11/12/2023 7:59,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,6.0,44.0,08B,1183071.0,1847869.0,2023,12/9/2023 15:41,41.737751,-87.604856,"(41.737750767, -87.604855911)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549994,1715153,G516233,8/27/2001 23:00,036XX S LAKE PARK AV,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,False,True,...,NaN,NaN,26,1182305.0,1881212.0,2001,8/17/2015 15:03,41.829265,-87.606630,"(41.829264761, -87.606629868)"
549995,1799889,G625392,10/16/2001 16:30,065XX S STEWART AV,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,NaN,NaN,5,1174713.0,1861451.0,2001,8/17/2015 15:03,41.775211,-87.635073,"(41.775211478, -87.635073388)"
549996,1769834,G583569,9/29/2001 5:35,031XX N CENTRAL PARK AV,460,BATTERY,SIMPLE,RESIDENCE,False,True,...,NaN,NaN,08B,1151878.0,1920763.0,2001,8/17/2015 15:03,41.938449,-87.717224,"(41.938448908, -87.717224032)"
549997,1788327,G610965,9/12/2001 9:05,065XX S CICERO AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,True,False,...,NaN,NaN,7,1145544.0,1861043.0,2001,8/17/2015 15:03,41.774692,-87.742015,"(41.774692006, -87.742014699)"
549998,1810693,G627247,10/18/2001 17:34,053XX W FERDINAND ST,2092,NARCOTICS,SOLICIT NARCOTICS ON PUBLICWAY,SIDEWALK,True,False,...,NaN,NaN,26,1140670.0,1902673.0,2001,8/17/2015 15:03,41.889022,-87.758862,"(41.889021585, -87.758861788)"

In [ ]:
# Set display option to show all columns
pd.set_option('display.max_columns', None)

In [ ]:
df.copy() # Create a copy of the DataFrame

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,8/25/2007 9:22,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,49.0,1.0,08A,NaN,NaN,2007,8/17/2015 15:03,NaN,NaN,NaN
1,25953,JE240540,5/24/2021 15:06,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,36.0,19.0,01A,1141387.0,1913179.0,2021,11/18/2023 15:39,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,6/26/2021 9:24,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,50.0,13.0,01A,1152781.0,1941458.0,2021,11/18/2023 15:39,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,11/9/2023 7:30,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,47.0,5.0,5,1162518.0,1925906.0,2023,11/18/2023 15:39,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,11/12/2023 7:59,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,6,6.0,44.0,08B,1183071.0,1847869.0,2023,12/9/2023 15:41,41.737751,-87.604856,"(41.737750767, -87.604855911)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549994,1715153,G516233,8/27/2001 23:00,036XX S LAKE PARK AV,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,False,True,2122,2,NaN,NaN,26,1182305.0,1881212.0,2001,8/17/2015 15:03,41.829265,-87.606630,"(41.829264761, -87.606629868)"
549995,1799889,G625392,10/16/2001 16:30,065XX S STEWART AV,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,722,7,NaN,NaN,5,1174713.0,1861451.0,2001,8/17/2015 15:03,41.775211,-87.635073,"(41.775211478, -87.635073388)"
549996,1769834,G583569,9/29/2001 5:35,031XX N CENTRAL PARK AV,460,BATTERY,SIMPLE,RESIDENCE,False,True,1412,14,NaN,NaN,08B,1151878.0,1920763.0,2001,8/17/2015 15:03,41.938449,-87.717224,"(41.938448908, -87.717224032)"
549997,1788327,G610965,9/12/2001 9:05,065XX S CICERO AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,True,False,833,8,NaN,NaN,7,1145544.0,1861043.0,2001,8/17/2015 15:03,41.774692,-87.742015,"(41.774692006, -87.742014699)"
549998,1810693,G627247,10/18/2001 17:34,053XX W FERDINAND ST,2092,NARCOTICS,SOLICIT NARCOTICS ON PUBLICWAY,SIDEWALK,True,False,1523,15,NaN,NaN,26,1140670.0,1902673.0,2001,8/17/2015 15:03,41.889022,-87.758862,"(41.889021585, -87.758861788)"

In [ ]:
# Display the first few rows of the DataFrame
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,8/25/2007 9:22,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,49.0,1.0,08A,NaN,NaN,2007,8/17/2015 15:03,NaN,NaN,NaN
1,25953,JE240540,5/24/2021 15:06,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,36.0,19.0,01A,1141387.0,1913179.0,2021,11/18/2023 15:39,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,6/26/2021 9:24,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,50.0,13.0,01A,1152781.0,1941458.0,2021,11/18/2023 15:39,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,11/9/2023 7:30,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,47.0,5.0,5,1162518.0,1925906.0,2023,11/18/2023 15:39,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,11/12/2023 7:59,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,6,6.0,44.0,08B,1183071.0,1847869.0,2023,12/9/2023 15:41,41.737751,-87.604856,"(41.737750767, -87.604855911)"

In [ ]:
# Display the last few rows of the DataFrame
df.tail()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
549994,1715153,G516233,8/27/2001 23:00,036XX S LAKE PARK AV,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,False,True,2122,2,NaN,NaN,26,1182305.0,1881212.0,2001,8/17/2015 15:03,41.829265,-87.606630,"(41.829264761, -87.606629868)"
549995,1799889,G625392,10/16/2001 16:30,065XX S STEWART AV,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,722,7,NaN,NaN,5,1174713.0,1861451.0,2001,8/17/2015 15:03,41.775211,-87.635073,"(41.775211478, -87.635073388)"
549996,1769834,G583569,9/29/2001 5:35,031XX N CENTRAL PARK AV,460,BATTERY,SIMPLE,RESIDENCE,False,True,1412,14,NaN,NaN,08B,1151878.0,1920763.0,2001,8/17/2015 15:03,41.938449,-87.717224,"(41.938448908, -87.717224032)"
549997,1788327,G610965,9/12/2001 9:05,065XX S CICERO AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,True,False,833,8,NaN,NaN,7,1145544.0,1861043.0,2001,8/17/2015 15:03,41.774692,-87.742015,"(41.774692006, -87.742014699)"
549998,1810693,G627247,10/18/2001 17:34,053XX W FERDINAND ST,2092,NARCOTICS,SOLICIT NARCOTICS ON PUBLICWAY,SIDEWALK,True,False,1523,15,NaN,NaN,26,1140670.0,1902673.0,2001,8/17/2015 15:03,41.889022,-87.758862,"(41.889021585, -87.758861788)"

In [ ]:
df.shape # Display the shape of the DataFrame

(549999, 22)

In [ ]:
df.info() # General information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549999 entries, 0 to 549998
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549999 non-null  int64
 1   Case Number           549999 non-null  object
 2   Date                  549999 non-null  object
 3   Block                 549999 non-null  object
 4   IUCR                  549999 non-null  object
 5   Primary Type          549999 non-null  object
 6   Description           549999 non-null  object
 7   Location Description  548326 non-null  object
 8   Arrest                549999 non-null  bool
 9   Domestic              549999 non-null  bool
 10  Beat                  549999 non-null  int64
 11  District              549999 non-null  int64
 12  Ward                  213674 non-null  float64
 13  Community Area        215093 non-null  float64
 14  FBI Code              549999 non-null  object
 15  X Coordinate          543087 non-null  float64
 16  Y Coordinate          543087 non-null  float64
 17  Year                  549999 non-null  int64
 18  Updated On            549999 non-null  object
 19  Latitude              543087 non-null  float64
 20  Longitude             543087 non-null  float64
 21  Location              543087 non-null  object
dtypes: bool(2), float64(6), int64(4), object(10)
memory usage: 85.0+ MB

In [ ]:
df.isnull().sum() # Display the number of missing values in each column

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1673
Arrest                       0
Domestic                     0
Beat                         0
District                     0
Ward                    336325
Community Area          334906
FBI Code                     0
X Coordinate              6912
Y Coordinate              6912
Year                         0
Updated On                   0
Latitude                  6912
Longitude                 6912
Location                  6912
dtype: int64

In [ ]:
df.columns # Display the column of the DataFrame

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [ ]:
# Generate descriptive statistics for both numerical and categorical columns
df.describe(include='all')

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
count,5.499990e+05,549999,549999,549999,549999,549999,549999,548326,549999,549999,549999.000000,549999.000000,213674.000000,215093.000000,549999,5.430870e+05,5.430870e+05,549999.000000,549999,543087.000000,543087.000000,543087
unique,NaN,549434,244168,51020,356,34,449,210,2,2,NaN,NaN,NaN,NaN,27,NaN,NaN,NaN,2272,NaN,NaN,278640
top,NaN,HZ140230,1/1/2024 0:00,100XX W OHARE ST,460,THEFT,SIMPLE,STREET,False,False,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,8/17/2015 15:03,NaN,NaN,"(41.976200173, -87.905312411)"
freq,NaN,6,88,1475,66750,112771,95252,166056,419279,457799,NaN,NaN,NaN,NaN,112771,NaN,NaN,NaN,321822,NaN,NaN,1324
mean,5.748380e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.364957,11.339984,23.064659,36.755436,NaN,1.164788e+06,1.886954e+06,2009.336524,NaN,41.845388,-87.670757,NaN
std,5.669909e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,712.157469,7.047229,13.876843,21.830825,NaN,1.890234e+04,3.530500e+04,10.728233,NaN,0.097231,0.067835,NaN
min,6.340000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.000000,1.000000,1.000000,1.000000,NaN,0.000000e+00,0.000000e+00,2001.000000,NaN,36.619446,-91.686566,NaN
25%,1.477682e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,621.000000,6.000000,10.000000,22.000000,NaN,1.153708e+06,1.860460e+06,2001.000000,NaN,41.772517,-87.711122,NaN
50%,1.651346e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1113.000000,10.000000,23.000000,32.000000,NaN,1.166408e+06,1.892009e+06,2001.000000,NaN,41.859379,-87.664750,NaN
75%,1.327660e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1813.000000,17.000000,34.000000,55.000000,NaN,1.176423e+06,1.910292e+06,2023.000000,NaN,41.909717,-87.627942,NaN
max,1.348547e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2535.000000,31.000000,50.000000,77.000000,NaN,1.205119e+06,1.951610e+06,2024.000000,NaN,42.022878,-87.524532,NaN

In [ ]:
# Count the number of duplicated rows in the DataFrame
df.duplicated().sum()

0

In [ ]:
# Convert 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Check the dtype of 'Date' column
df['Date'].dtype

# Rename 'Date' column to 'Date Time'
df.rename(columns={'Date': 'Date Time'}, inplace=True)

In [ ]:
# Convert 'Updated On' column to datetime format
df['Updated On'] = pd.to_datetime(df['Updated On'])

# Check the dtype of 'Updated On' column
df['Updated On'].dtype

dtype('<M8[ns]')

In [ ]:
df.head() # Check the first 10 rows after conversion

,ID,Case Number,Date Time,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:00,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,49.0,1.0,08A,NaN,NaN,2007,2015-08-17 15:03:00,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,36.0,19.0,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:00,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,50.0,13.0,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:00,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:00,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,6,6.0,44.0,08B,1183071.0,1847869.0,2023,2023-12-09 15:41:00,41.737751,-87.604856,"(41.737750767, -87.604855911)"

In [ ]:
df.info() # Check the information about 'Date' and 'Updated On' column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549999 entries, 0 to 549998
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549999 non-null  int64
 1   Case Number           549999 non-null  object
 2   Date Time             549999 non-null  datetime64[ns]
 3   Block                 549999 non-null  object
 4   IUCR                  549999 non-null  object
 5   Primary Type          549999 non-null  object
 6   Description           549999 non-null  object
 7   Location Description  548326 non-null  object
 8   Arrest                549999 non-null  bool
 9   Domestic              549999 non-null  bool
 10  Beat                  549999 non-null  int64
 11  District              549999 non-null  int64
 12  Ward                  213674 non-null  float64
 13  Community Area        215093 non-null  float64
 14  FBI Code              549999 non-null  object
 15  X Coordinate          543087 non-null  float64
 16  Y Coordinate          543087 non-null  float64
 17  Year                  549999 non-null  int64
 18  Updated On            549999 non-null  datetime64[ns]
 19  Latitude              543087 non-null  float64
 20  Longitude             543087 non-null  float64
 21  Location              543087 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(6), int64(4), object(8)
memory usage: 85.0+ MB

In [ ]:
# Apply the regex to clean the 'IUCR' column
df['IUCR'] = df['IUCR'].str.replace(r'^0+(\d+)[A-Za-z]*$', r'\1', regex=True)

# Check the first 10 rows after transformation
df['IUCR'].head(10)

0     560
1     110
2     110
3     620
4     454
5     820
6    1320
7    1153
8     281
9     820
Name: IUCR, dtype: object

In [ ]:
# Apply the regex to clean the 'FBI Code' column
df['FBI Code'] = df['FBI Code'].str.replace(r'^0+(\d+)[A-Za-z]*$', r'\1', regex=True)

# Check the first 10 rows after transformation
df['FBI Code'].head(10)

0     8
1     1
2     1
3     5
4     8
5     6
6    14
7    11
8     2
9     6
Name: FBI Code, dtype: object

In [ ]:
# Replacement dictionary
replace_case_num={
    'G 050552':'G050552',
    '01G050460':'G050460'
}

# Apply the replacement
df['Case Number'] = df['Case Number'].apply(lambda x: replace_case_num.get(x, x))
df.head(10)

,ID,Case Number,Date Time,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:00,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,49.0,1.0,8,NaN,NaN,2007,2015-08-17 15:03:00,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,36.0,19.0,1,1141387.0,1913179.0,2021,2023-11-18 15:39:00,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,50.0,13.0,1,1152781.0,1941458.0,2021,2023-11-18 15:39:00,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:00,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,6,6.0,44.0,8,1183071.0,1847869.0,2023,2023-12-09 15:41:00,41.737751,-87.604856,"(41.737750767, -87.604855911)"
5,1930689,HH109118,2002-01-05 21:24:00,007XX E 103 ST,820,THEFT,$500 AND UNDER,GAS STATION,True,False,512,5,NaN,NaN,6,NaN,NaN,2002,2016-02-04 06:33:00,NaN,NaN,NaN
6,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,122,1,42.0,32.0,14,1174694.0,1901831.0,2023,2023-11-04 15:40:00,41.886018,-87.633938,"(41.886018055, -87.633937881)"
7,13210088,JG423627,2023-08-31 12:00:00,023XX W JACKSON BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,1225,12,27.0,28.0,11,1160870.0,1898642.0,2023,2023-09-16 15:41:00,41.877565,-87.684791,"(41.877565108, -87.68479102)"
8,13210004,JG422532,2023-07-24 21:45:00,073XX S JEFFERY BLVD,281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,333,3,7.0,43.0,2,1190812.0,1856743.0,2023,2023-09-16 15:41:00,41.761919,-87.576209,"(41.7619185, -87.576209245)"
9,13210062,JG423596,2023-08-27 07:00:00,034XX N LAWNDALE AVE,820,THEFT,$500 AND UNDER,APARTMENT,False,False,1732,17,30.0,21.0,6,1151117.0,1922554.0,2023,2023-09-16 15:41:00,41.943379,-87.719974,"(41.943378528, -87.7199738)"

In [ ]:
# Replacement dictionary
replace_primary_type={
    'CRIM SEXUAL ASSAULT':'CRIMINAL SEXUAL ASSAULT'
}

# Apply the replacement
df['Primary Type'] = df['Primary Type'].apply(lambda x: replace_case_num.get(x, x))
df.head(10)

,ID,Case Number,Date Time,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:00,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,49.0,1.0,8,NaN,NaN,2007,2015-08-17 15:03:00,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,36.0,19.0,1,1141387.0,1913179.0,2021,2023-11-18 15:39:00,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,50.0,13.0,1,1152781.0,1941458.0,2021,2023-11-18 15:39:00,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:00,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,6,6.0,44.0,8,1183071.0,1847869.0,2023,2023-12-09 15:41:00,41.737751,-87.604856,"(41.737750767, -87.604855911)"
5,1930689,HH109118,2002-01-05 21:24:00,007XX E 103 ST,820,THEFT,$500 AND UNDER,GAS STATION,True,False,512,5,NaN,NaN,6,NaN,NaN,2002,2016-02-04 06:33:00,NaN,NaN,NaN
6,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,122,1,42.0,32.0,14,1174694.0,1901831.0,2023,2023-11-04 15:40:00,41.886018,-87.633938,"(41.886018055, -87.633937881)"
7,13210088,JG423627,2023-08-31 12:00:00,023XX W JACKSON BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,1225,12,27.0,28.0,11,1160870.0,1898642.0,2023,2023-09-16 15:41:00,41.877565,-87.684791,"(41.877565108, -87.68479102)"
8,13210004,JG422532,2023-07-24 21:45:00,073XX S JEFFERY BLVD,281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,333,3,7.0,43.0,2,1190812.0,1856743.0,2023,2023-09-16 15:41:00,41.761919,-87.576209,"(41.7619185, -87.576209245)"
9,13210062,JG423596,2023-08-27 07:00:00,034XX N LAWNDALE AVE,820,THEFT,$500 AND UNDER,APARTMENT,False,False,1732,17,30.0,21.0,6,1151117.0,1922554.0,2023,2023-09-16 15:41:00,41.943379,-87.719974,"(41.943378528, -87.7199738)"

In [ ]:
df['Description'].nunique()

449

In [ ]:
df['Description'].unique()

array(['SIMPLE', 'FIRST DEGREE MURDER', 'UNLAWFUL ENTRY',
       'AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY',
       '$500 AND UNDER', 'TO VEHICLE',
       'FINANCIAL IDENTITY THEFT OVER $ 300', 'NON-AGGRAVATED',
       'TO PROPERTY', 'OVER $500', 'FORGERY', 'FROM BUILDING',
       'BOGUS CHECK', 'CHILD ABDUCTION', 'AUTOMOBILE',
       'ATTEMPT - FINANCIAL IDENTITY THEFT', 'ARMED - HANDGUN',
       'PREDATORY', 'VEHICULAR HIJACKING',
       'SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
       'INDECENT SOLICITATION OF A CHILD',
       'HARASSMENT BY ELECTRONIC MEANS',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'SEXUAL EXPLOITATION OF A CHILD',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE', 'RECKLESS FIREARM DISCHARGE',
       'CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'DOMESTIC BATTERY SIMPLE',
       'AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
       'CYBERSTALKING', 'AGGRAVATED - OTHER', 'RETAIL THEFT',
       'TO STATE SUP LAND', 'THEFT OF LOST / MISLAID PROPERTY', 'TO LAND',
       'ATTEMPT - AUTOMOBILE',
       'AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON',
       'OTHER VEHICLE OFFENSE', 'FALSE / STOLEN / ALTERED TRP',
       'AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
       'VEHICLE TITLE / REGISTRATION OFFENSE', 'AGGRAVATED - HANDGUN',
       'STRONG ARM - NO WEAPON', 'SOLICITING FOR BUSINESS',
       'ILLEGAL USE CASH CARD', 'BY FIRE', 'TO STATE SUPPORTED PROPERTY',
       'TELEPHONE THREAT', 'ATTEMPT FORCIBLE ENTRY', 'FORCIBLE ENTRY',
       'VIOLATE ORDER OF PROTECTION', 'POSSESS - CRACK', 'TO RESIDENCE',
       'THEFT / RECOVERY - AUTOMOBILE',
       'AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY',
       'ENDANGERING LIFE / HEALTH OF CHILD', 'UNLAWFUL RESTRAINT',
       'AGGRAVATED', 'ARMED - OTHER FIREARM',
       'ARMED - OTHER DANGEROUS WEAPON', 'CRIMINAL SEXUAL ABUSE',
       'FRAUD OR CONFIDENCE GAME', 'AGGRAVATED - OTHER DANGEROUS WEAPON',
       'PROHIBITED PLACES', 'OTHER OFFENSE',
       'UNLAWFUL POSSESSION - HANDGUN', 'COUNTERFEITING DOCUMENT',
       'TO CITY OF CHICAGO PROPERTY', 'THEFT OF LABOR / SERVICES',
       'POSSESS - HEROIN (WHITE)', 'CREDIT CARD FRAUD',
       'RESIST / OBSTRUCT / DISARM OFFICER',
       'AGGRAVATED VEHICULAR HIJACKING',
       'NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL IMAGES',
       'THEFT BY LESSEE, MOTOR VEHICLE', 'BOMB THREAT',
       'FINANCIAL EXPLOITATION OF AN ELDERLY OR DISABLED PERSON',
       'AGGRAVATED - HANDS, FISTS, FEET, SERIOUS INJURY',
       'OTHER VIOLATION', 'CYCLE, SCOOTER, BIKE WITH VIN', 'CHILD ABUSE',
       'POSSESS - HEROIN (BLACK TAR)', 'ATTEMPT ARMED - HANDGUN',
       'PROTECTED EMPLOYEE - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'POCKET-PICKING', 'UNLAWFUL USE - OTHER FIREARM',
       'AGG. PROTECTED EMPLOYEE - HANDS, FISTS, FEET, SERIOUS INJURY',
       'POSSESS - BARBITURATES', 'OTHER CRIME AGAINST PERSON',
       'ATTEMPT AGGRAVATED', 'HOME INVASION',
       'ILLEGAL POSSESSION CASH CARD', 'LICENSE VIOLATION',
       'STOLEN PROPERTY BUY / RECEIVE / POSSESS',
       'HARASSMENT BY TELEPHONE', 'POSSESS - CANNABIS MORE THAN 30 GRAMS',
       'FINANCIAL IDENTITY THEFT $300 AND UNDER',
       'ATTEMPT - CYCLE, SCOOTER, BIKE WITH VIN',
       'SOLICIT NARCOTICS ON PUBLIC WAY', 'COMPUTER FRAUD',
       'POSSESS - COCAINE', 'POSSESS - SYNTHETIC DRUGS',
       'VIOLATION OF STALKING NO CONTACT ORDER',
       'AGGRAVATED FINANCIAL IDENTITY THEFT',
       'UNLAWFUL USE - OTHER DANGEROUS WEAPON',
       'MANUFACTURE / DELIVER - CANNABIS OVER 10 GRAMS',
       'AGGRAVATED OF A SENIOR CITIZEN', 'EMBEZZLEMENT',
       'CHILD PORNOGRAPHY', 'ATTEMPT THEFT', 'COUNTERFEIT CHECK', 'OTHER',
       'PUBLIC INDECENCY',
       'AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT',
       'GUN OFFENDER - ANNUAL REGISTRATION', 'FALSE POLICE REPORT',
       'FOUND SUSPECT NARCOTICS',
       'AGGRAVATED PROTECTED EMPLOYEE - OTHER DANGEROUS WEAPON',
       'AGGRAVATED DOMESTIC BATTERY - HANDGUN',
       'AGGRAVATED - OTHER FIREARM', 'OBSTRUCTING SERVICE',
       'GUN OFFENDER - DUTY TO REGISTER',
       'AGGRAVATED - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'ATTEMPT ARSON', 'CRIMINAL DEFACEMENT',
       'POSSESSION OF BURGLARY TOOLS',
       'ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT', 'RECKLESS CONDUCT',
       'PURSE-SNATCHING', 'VIOLATION GPS MONITORING DEVICE',
       'AGGRAVATED OF A CHILD', 'POSSESS - CANNABIS 30 GRAMS OR LESS',
       'ANIMAL ABUSE / NEGLECT', 'OBSCENE TELEPHONE CALLS',
       'ATTEMPT STRONG ARM - NO WEAPON',
       'THEFT / RECOVERY - CYCLE, SCOOTER, BIKE WITH VIN',
       'AGGRAVATED POLICE OFFICER - HANDGUN',
       'OTHER CRIME INVOLVING PROPERTY', 'KIDNAPPING',
       'OBSTRUCTING JUSTICE',
       'SALE / DISTRIBUTE OBSCENE MATERIAL TO MINOR', 'EMPLOY MINOR',
       'ARMED - KNIFE / CUTTING INSTRUMENT',
       'POSSESSION OF DRUG EQUIPMENT',
       'AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET, NO INJURY',
       'OF AN UNBORN CHILD', 'SELL / GIVE / DELIVER LIQUOR TO MINOR',
       'INTIMIDATION', 'POSSESS - HALLUCINOGENS', 'POSSESS - PCP',
       'CHILD ABDUCTION / STRANGER', 'DECEPTIVE COLLECTION PRACTICES',
       'UNLAWFUL POSSESSION - AMMUNITION', 'UNLAWFUL USE - HANDGUN',
       'AGGRAVATED POLICE OFFICER - KNIFE / CUTTING INSTRUMENT',
       'AGGRAVATED COMPUTER TAMPERING',
       'CONTRIBUTE TO THE DELINQUENCY OF CHILD', 'TRUCK, BUS, MOTOR HOME',
       'ARMED: HANDGUN',
       'AGGRAVATED P.O. - HANDS, FISTS, FEET, SERIOUS INJURY',
       'SEX OFFENDER - FAIL TO REGISTER', 'INVOLUNTARY SERVITUDE',
       'VIOLATION OF CIVIL NO CONTACT ORDER', 'GAME/DICE',
       'OBSTRUCTING IDENTIFICATION', 'ATTEMPT NON-AGGRAVATED',
       'AGGRAVATED PROTECTED EMPLOYEE - KNIFE / CUTTING INSTRUMENT',
       'UNAUTHORIZED VIDEOTAPING',
       'MANUFACTURE / DELIVER -  HEROIN (WHITE)',
       'LIQUOR LICENSE VIOLATION', 'SOLICIT ON PUBLIC WAY',
       'AGGRAVATED POLICE OFFICER - OTHER DANGEROUS WEAPON',
       'CYCLE, SCOOTER, BIKE NO VIN',
       'VIOLENT OFFENDER - DUTY TO REGISTER',
       'UNLAWFUL USE OF A COMPUTER', 'CHILD ABANDONMENT',
       'POSSESS - METHAMPHETAMINE', 'ESCAPE', 'ARMED VIOLENCE',
       'OBSCENE MATTER', 'SEX OFFENDER - FAIL TO REGISTER NEW ADDRESS',
       'ATTEMPT ARMED - OTHER DANGEROUS WEAPON', 'EXTORTION',
       'POSS: COCAINE', 'UNLAWFUL SALE - HANDGUN',
       'OTHER WEAPONS VIOLATION', 'MANUFACTURE / DELIVER - CRACK',
       'MANUFACTURE / DELIVER - CANNABIS 10 GRAMS OR LESS',
       'AGGRAVATED PROTECTED EMPLOYEE - HANDGUN', 'IMPERSONATION',
       'POSS: HEROIN(WHITE)', 'POSS: CRACK',
       'THEFT / RECOVERY - TRUCK, BUS, MOBILE HOME',
       'POSSESS - HEROIN (TAN / BROWN TAR)',
       'UNLAWFUL VISITATION INTERFERENCE', 'FORFEIT PROPERTY',
       'ALTER / FORGE PRESCRIPTION', 'SOLICIT OFF PUBLIC WAY',
       'POSSESS FIREARM / AMMUNITION - NO FOID CARD',
       'THEFT BY LESSEE, NON-MOTOR VEHICLE', 'DELIVERY CONTAINER THEFT',
       'ATTEMPT AGGRAVATED - OTHER', 'ARSON THREAT',
       'GUN OFFENDER - DUTY TO REPORT CHANGE OF INFORMATION',
       'TAMPER WITH MOTOR VEHICLE', 'UNLAWFUL POSSESSION - OTHER FIREARM',
       'MANUFACTURE / DELIVER - METHAMPHETAMINE', 'TO AIRPORT',
       'PEEPING TOM', 'ARMED WHILE UNDER THE INFLUENCE',
       'ATTEMPT ARMED - OTHER FIREARM',
       'TIRE DEFLATION DEVICE DEPLOYMENT', 'PAROLE VIOLATION',
       'AGGRAVATED: HANDGUN', 'UNLAWFUL USE / SALE OF AIR RIFLE',
       'POSSESSION OF PORNOGRAPHIC PRINT',
       'VIOLATION OF BAIL BOND - DOMESTIC VIOLENCE',
       'BOARD PLANE WITH WEAPON', 'POSSESS - AMPHETAMINES',
       'CRIMINAL DRUG CONSPIRACY',
       'THEFT / RECOVERY - CYCLE, SCOOTER, BIKE NO VIN',
       'SEX OFFENDER - PROHIBITED ZONE', 'ATTEMPT CRIMINAL SEXUAL ABUSE',
       'SEXUAL RELATIONS IN FAMILY', 'INSURANCE FRAUD',
       'INSTITUTIONAL VANDALISM',
       'MANUFACTURE / DELIVER - HEROIN (TAN / BROWN TAR)',
       'STRONGARM - NO WEAPON', 'ATTEMPT - TRUCK, BUS, MOTOR HOME',
       'HAZARDOUS MATERIALS VIOLATION', 'ATTEMPT AGGRAVATED - HANDGUN',
       'ABUSE / NEGLECT - CARE FACILITY', 'MANU/DELIVER:CRACK',
       'MOB ACTION', 'OBSCENITY', 'MANUFACTURE / DELIVER - COCAINE',
       'RECKLESS HOMICIDE', 'COMMERCIAL SEX ACTS', 'FORCIBLE DETENTION',
       'ATT: AUTOMOBILE', '$300 AND UNDER',
       'MANUFACTURE / DELIVER - BARBITURATES',
       'MANUFACTURE / DELIVER - SYNTHETIC DRUGS', 'EAVESDROPPING',
       'ATTEMPT - CYCLE, SCOOTER, BIKE NO VIN',
       'OTHER ARSON / EXPLOSIVE INCIDENT', 'PUBLIC DEMONSTRATION',
       'INTERFERENCE JUDICIAL PROCESS', 'BIGAMY',
       'ILLEGAL POSSESSION BY MINOR',
       'AGGRAVATED PROTECTED EMPLOYEE - OTHER FIREARM',
       'VIOLENT OFFENDER - FAIL TO REGISTER NEW ADDRESS',
       'MANUFACTURE / DELIVER - AMPHETAMINES',
       'VIOLENT OFFENDER - ANNUAL REGISTRATION',
       'OTHER PROSTITUTION OFFENSE',
       'ATTEMPT AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
       'MANUFACTURE / DELIVER - HALLUCINOGEN', 'BRIBERY',
       'INTOXICATING COMPOUNDS', 'VIOLATION OF SMOKING BAN',
       'SALE / DELIVER - DRUG PARAPHERNALIA',
       'CONCEALED CARRY LICENSE REVOCATION', 'FORNICATION',
       'AGG: FINANCIAL ID THEFT', 'PAY TV SERVICE OFFENSES',
       'LICENSED PREMISE', 'AGGRAVATED POLICE OFFICER - OTHER FIREARM',
       'FALSE FIRE ALARM', 'POSSESSION - EXPLOSIVE / INCENDIARY DEVICE',
       'FROM COIN-OPERATED MACHINE OR DEVICE',
       'AGGRAVATED OF AN UNBORN CHILD', 'ARSONIST - ANNUAL REGISTRATION',
       'ATTEMPT AGGRAVATED CRIMINAL SEXUAL ABUSE',
       'AGG CRIM SEX ABUSE FAM MEMBER', 'MANU/DELIVER: HEROIN (WHITE)',
       'INTERFERE WITH EMERGENCY EQUIPMENT',
       'CRIM SEX ABUSE BY FAM MEMBER', 'AGG CRIMINAL SEXUAL ABUSE',
       'POSS: CANNABIS MORE THAN 30GMS', 'POSSESS - LOOK-ALIKE DRUGS',
       'SEX ASSLT OF CHILD BY FAM MBR', 'HARBOR RUNAWAY',
       'AGG SEX ASSLT OF CHILD FAM MBR',
       'AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON',
       'FINAN EXPLOIT-ELDERLY/DISABLED', 'ATT CRIM SEXUAL ABUSE',
       'AGGRAVATED: OTHER',
       'CONTRIBUTE TO THE CRIMINAL DELINQUENCY OF CHILD',
       'MANUFACTURE / DELIVER - SYNTHETIC MARIJUANA',
       'MANU/DEL:CANNABIS 10GM OR LESS', 'POSS: HALLUCINOGENS',
       'THEFT/RECOVERY: AUTOMOBILE', 'INDECENT SOLICITATION/CHILD',
       'INTIMIDATION OF LAW ENFORCEMENT OFFICIAL',
       'DELIVER CANNABIS TO PERSON UNDER 18',
       'INDECENT SOLICITATION OF AN ADULT', 'MANUFACTURE / DELIVER - PCP',
       'CANNABIS PLANT', 'CRIMINAL TRANSMISSION OF HIV',
       'UNLAWFUL SALE - DELIVERY OF FIREARM AT SCHOOL',
       'ATTEMPT POSSESSION NARCOTICS',
       'AGGRAVATED DOMESTIC BATTERY: HANDS/FIST/FEET SERIOUS INJURY',
       'ILLEGAL CONSUMPTION BY MINOR',
       'ATTEMPT AGGRAVATED - OTHER DANGEROUS WEAPON',
       'ALTER/FORGE PRESCRIPTION', 'FALSE/STOLEN/ALTERED TRP',
       'BY EXPLOSIVE',
       'FAILURE TO MAINTAIN RECORDS - CONTROLLED SUBSTANCES',
       'ATTEMPT POSSESSION CANNABIS', 'POSSESSION - SYNTHETIC MARIJUANA',
       'AGGRAVATED: OTHER DANG WEAPON', 'POSS: CANNABIS 30GMS OR LESS',
       'ADULTRY', 'OFFICIAL MISCONDUCT',
       'ATTEMPT AGGRAVATED - OTHER FIREARM',
       'SEX OFFENDER: FAIL REG NEW ADD',
       'MANUFACTURE / DELIVER - LOOK-ALIKE DRUG',
       'THEFT OF LABOR/SERVICES',
       'AGGRAVATED DOMESTIC BATTERY - OTHER FIREARM',
       'INVOLUNTARY MANSLAUGHTER',
       'DEFACE IDENTIFICATION MARKS OF FIREARM', 'MONEY LAUNDERING',
       'LOOTING', 'AGG: HANDS/FIST/FEET NO/MINOR INJURY',
       'AGGRAVATED:KNIFE/CUTTING INSTR', 'ENDANGERING LIFE/HEALTH CHILD',
       'VIO BAIL BOND: DOM VIOLENCE', 'AGGRAVATED DOMESTIC BATTERY',
       'TO STATE SUP PROP', 'FINANCIAL ID THEFT:$300 &UNDER',
       'AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST',
       'FINANCIAL ID THEFT: OVER $300',
       'FINANCIAL IDENTITY THEFT: $300 & UNDER',
       'NON-CONSENSUAL DISSEMINATION PRIVATE SEXUAL IMAGES',
       'ATTEMPT: STRONGARM-NO WEAPON', 'ATTEMPT: ARMED-HANDGUN',
       'AGGRAVATED: OTHER FIREARM', 'POSS: SYNTHETIC DRUGS',
       'CHILD ABDUCTION/STRANGER', 'POSS: HEROIN(BRN/TAN)',
       'AGG PO HANDS NO/MIN INJURY', 'ATTEMPT: AGGRAVATED',
       'SOLICIT FOR BUSINESS', 'ARMED:KNIFE/CUTTING INSTRUMENT',
       'CALL OPERATION', 'SOLICIT NARCOTICS ON PUBLICWAY',
       'UNLAWFUL POSS OF HANDGUN', 'UNLAWFUL USE OTHER DANG WEAPON',
       'THEFT BY LESSEE,NON-VEH', 'MANU/DEL:CANNABIS OVER 10 GMS',
       'UNLAWFUL POSS AMMUNITION', 'SEX OFFENDER: FAIL TO REGISTER',
       'THEFT OF LOST/MISLAID PROP', 'UNLAWFUL INTERFERE/VISITATION',
       'THEFT BY LESSEE,MOTOR VEH', 'ARMED: OTHER DANGEROUS WEAPON',
       'SELL/GIVE/DEL LIQUOR TO MINOR', 'SALE/DEL HYPODERMIC NEEDLE',
       'AGGRAVATED: KNIFE/CUT INSTR', 'AGG RITUAL MUT:KNIFE/CUTTING I',
       'AGG PRO.EMP:KNIFE/CUTTING INST', 'ATT: TRUCK, BUS, MOTOR HOME',
       'ATTEMPT: ARMED-KNIFE/CUT INSTR', 'CYCLE, SCOOTER, BIKE W-VIN',
       'STOLEN PROP: BUY/RECEIVE/POS.', 'MANU/DELIVER:PCP',
       'UNLAWFUL POSS OTHER FIREARM', 'THEFT/RECOVERY: TRUCK,BUS,MHOME',
       'POSS: PCP', 'ATTEMPT: ARMED-OTHER DANG WEAP',
       'GAME/AMUSEMENT DEVICE', 'ATTEMPT: ARMED-OTHER FIREARM',
       'MANU/DELIVER:LOOK-ALIKE DRUG', 'UNLAWFUL USE HANDGUN',
       'POS: HYPODERMIC NEEDLE', 'AGG PRO.EMP: HANDGUN',
       'UNLAWFUL USE/SALE AIR RIFLE', 'UNLAWFUL USE OTHER FIREARM',
       'ATTEMPT AGG: KNIFE/CUT INSTR', 'PRO EMP HANDS NO/MIN INJURY',
       'CONTRIBUTE DELINQUENCY OF A CHILD', 'AGGRAVATED PO: HANDGUN',
       'ARMED: OTHER FIREARM', 'RESIST/OBSTRUCT/DISARM OFFICER',
       'UNLAWFUL USE OF RECORDED SOUND', 'ATTEMPT AGG: OTHER DANG WEAPON',
       'UNLAWFUL SALE HANDGUN', 'AGGRAVATED PO: KNIFE/CUT INSTR',
       'MANU/DELIVER:COCAINE', 'ATT AGG CRIMINAL SEXUAL ABUSE',
       'AGG RITUAL MUT:OTH DANG WEAPON', 'PATRONIZING A PROSTITUTE',
       'WIREROOM/SPORTS', 'POSS FIREARM/AMMO:NO FOID CARD', 'GAME/CARDS',
       'AGGRAVATED PO: OTHER DANG WEAP', 'MANU/DELIVER:HEROIN(BLACK TAR)',
       'POSS: AMPHETAMINES', 'CAB OPERATION',
       'MANU/DELIVER: HALLUCINOGEN', 'POSS: BARBITUATES',
       'POSS: HEROIN(BLACK TAR)', 'TO FIRE FIGHT.APP.EQUIP',
       'POSS: LOOK-ALIKE DRUGS', 'MANU/DELIVER: HEROIN(BRN/TAN)',
       'VIOL CHARITABLE GAME ACT', 'AGGRAVATED PO: OTHER FIREARM',
       'DELIVER CANNABIS TO PERSON <18', 'MANU/DELIVER:AMPHETAMINES',
       'THEFT/RECOVERY: CYCLE, SCOOTER, BIKE W-VIN',
       'MANU/DELIVER:BARBITUATES', 'INDECENT SOLICITATION/ADULT',
       'AGGRAVATED PO:KNIFE/CUT INSTR', 'BOOKMAKING/SPORTS',
       'UNLAWFUL SALE OTHER FIREARM', 'DOMESTIC VIOLENCE',
       'REGISTER OF SALES BY DEALER', 'AGG PRO.EMP: OTHER DANG WEAPON',
       'ILLEGAL ILL LOTTERY', 'ATTEMPT AGG: HANDGUN',
       'SOLICIT FOR PROSTITUTE', 'MANU/DELIVER:SYNTHETIC DRUGS',
       'ATTEMPT AGG: OTHER', 'PIMPING', 'MINOR MISREPRESENT AGE',
       'IN TAVERN', 'PANDERING', 'POS: EXPLOSIVE/INCENDIARY DEV',
       'LOTTERY/OTHER', 'OTHER ARSON/EXPLOSIVE INCIDENT',
       'ATTEMPT: CYCLE, SCOOTER, BIKE W-VIN', 'BOOKMAKING/HORSES',
       'OVER $300', 'KEEP PLACE OF PROSTITUTION',
       'SALE/DIST OBSCENE MAT TO MINOR',
       'FINANCIAL IDENTITY THEFT: OVER $300',
       'POSS. KEYS OR DEV.TO COIN MACH', 'WIREROOM/HORSES',
       'ATT AGG CRIM SEXUAL ABUSE', 'DEFACE IDENT MARKS OF FIREARM',
       'POLICY/OTHER', 'REFUSING TO AID AN OFFICER',
       'DEL CONT SUBS TO PERSON <18', 'CONCEALING/AIDING A FUGITIVE',
       'SEX RELATION IN FAMILY', 'AGG RITUAL MUT:HANDGUN',
       'SEX OFFENDER: PROHIBITED ZONE', 'BOLITA OR BOLI PUL/WRITER',
       'BOLITA OR BOLI PUL/RUNNER'], dtype=object)

In [ ]:
# Replacement dictionary
replace_description = {
    'VIO BAIL BOND: DOM VIOLENCE':'VIOLATION OF BAIL BOND - DOMESTIC VIOLENCE',
    'VIOL CHARITABLE GAME ACT':'VIOLATION CHARITABLE GAME ACT',
    'UNLAWFUL POSS OF HANDGUN':'UNLAWFUL POSSESSION - HANDGUN',
    'UNLAWFUL SALE - HANDGUN':'UNLAWFUL SALE HANDGUN',
    'UNLAWFUL POSS AMMUNITION':'UNLAWFUL POSSESSION AMMUNITION',
    'UNLAWFUL POSSESSION - AMMUNITION':'UNLAWFUL POSSESSION AMMUNITION',
    'UNLAWFUL USE - OTHER FIREARM':'UNLAWFUL USE OTHER FIREARM',
    'UNLAWFUL USE OTHER DANG WEAPON': 'UNLAWFUL USE OTHER DANGEROUS WEAPON',
    'UNLAWFUL POSS OTHER FIREARM':'UNLAWFUL POSSESSION - OTHER FIREARM',
    'UNLAWFUL USE/SALE OF AIR RIFLE':'UNLAWFUL USE / SALE OF AIR RIFLE',
    'UNLAWFUL USE - HANDGUN':'UNLAWFUL USE HANDGUN',
    'TO STATE SUP PROP':'TO STATE SUPPORTED PROPERTY',
    'TO STATE SUP LAND':'TO STATE SUPPORTED LAND',
    'TO FIRE FIGHT.APP.EQUIP':'TO FIRE FIGHT APP EQUIPMENT',
    'RESIST/OBSTRUCT/DISARM OFFICER':'RESIST / OBSTRUCT / DISARM OFFICER',
    'THEFT OF LABOR/SERVICES':'THEFT OF LABOR / SERVICES',
    'THEFT OF LOST/MISLAID PROP':'THEFT OF LOST / MISLAID PROPERTY',
    'THEFT/RECOVERY: AUTOMOBILE':'THEFT / RECOVERY - AUTOMOBILE',
    'THEFT/RECOVERY: CYCLE, SCOOTER, BIKE W-VIN':'THEFT / RECOVERY - CYCLE, SCOOTER, BIKE WITH VIN',
    'THEFT/RECOVERY: TRUCK,BUS,MHOME':'THEFT / RECOVERY - TRUCK, BUS, MOBILE HOME',
    'THEFT/RECOVERY: TRUCK,BUS,MOBILE HOME':'THEFT / RECOVERY - TRUCK, BUS, MOBILE HOME',
    'THEFT BY LESSEE,NON-VEH':'THEFT BY LESSEE, NON-MOTOR VEHICLE',
    'THEFT BY LESSEE,MOTOR VEH':'THEFT BY LESSEE, NON-MOTOR VEHICLE',
    'STOLEN PROP: BUY/RECEIVE/POS.':'STOLEN PROPERTY BUY / RECEIVE / POSSESS',
    'SOLICIT NARCOTICS ON PUBLICWAY':'SOLICIT NARCOTICS ON PUBLIC WAY',
    'STRONGARM - NO WEAPON':'STRONG ARM - NO WEAPON',
    'SALE/DEL HYPODERMIC NEEDLE':'SALE / DELIVER - HYPODERMIC NEEDLE',
    'SALE/DIST OBSCENCE MAT TO MINOR':'SALE / DISTRIBUTE OBSCENCE MATERIAL TO MINOR',
    'SELL/GIVE/DEL LIQUOR TO MINOR':'SELL / GIVE / DELIVER LIQUOR TO MINOR',
    'SEX ASSLT OF CHILD BY FAM MBR':'SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
    'SEX OFFENDER - FAIL TO REGISTER':'SEX OFFENDER: FAIL TO REGISTER',
    'SEX OFFENDER: FAIL REG NEW ADD':'SEX OFFENDER - FAIL TO REGISTER NEW ADDRESS',
    'SEX OFFENDER - PROHIBITED ZONE':'SEX OFFENDER: PROHIBITED ZONE',
    'SEX RELATION IN FAMILY':'SEXUAL RELATIONS IN FAMILY',
    'POS: EXPLOSIVE/INCENDIARY DEV': 'POSSESSION - EXPLOSIVE / INCENDIARY DEVICE',
    'POS: HYPODERMIC NEEDLE':'POSSESSION - HYPODERMIC NEEDLE',
    'POSS FIREARM/AMMO:NO FOID CARD': 'POSSESS FIREARM / AMMUNITION - NO FOID CARD',
    'POSS. KEYS OR DEV.TO COIN MACH':'POSSESS KEYS OR DEVICE TO COIN MACHINE',
    'POSS: AMPHETAMINES':'POSSESS - AMPHETAMINES',
    'POSS: BARBITUATES':'POSSESS - BARBITUATES',
    'POSS: CANNABIS 30GMS OR LESS':'POSSESS - CANNABIS 30GMS OR LESS',
    'POSS: CANNABIS MORE THAN 30GMS':'POSSESS - CANNABIS MORE THAN 30GMS',
    'POSS: COCAINE':'POSSESS - COCAINE',
    'POSS: CRACK':'POSSESS - CRACK',
    'POSS: HALLUCINOGENS':'POSSESS - HALLUCINOGENS',
    'POSS: HEROIN(BLACK TAR)':'POSSESS - HEROIN(BLACK TAR)',
    'POSS: HEROIN(BRN/TAN)':'POSSESS - HEROIN(TAN / BROWN TAR)',
    'POSS: HEROIN(WHITE)':'POSSESS HEROIN(WHITE)',
    'POSS: PCP':'POSSESS - PCP',
    'POSS: SYNTHETIC DRUGS': 'POSSESS - SYNTHETIC DRUGS',
    'POSS: LOOK-ALIKE DRUGS':'POSSESS - LOOK-ALIKE DRUGS',
    'PRO EMP HANDS NO/MIN INJURY':'PROTECTED EMPLOYEE - HANDS, NO / MINOR INJURY',
    'GAME/AMUSEMENT DEVICE':'GAME / AMUSEMENT DEVICE',
    'GAME/CARDS':'GAME / CARDS',
    'GAME/DICE':'GAME / DICE',
    'NON-CONSENSUAL DISSEMINATION PRIVATE SEXUAL IMAGES':'NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL IMAGES',
    'OTHER ARSON/EXPLOSIVE INCIDENT':'OTHER ARSON / EXPLOSIVE INCIDENT',
    'MANU/DEL:CANNABIS 10GM OR LESS':'MANUFACTURE / DELIVER - CANNABIS 10 GRAMS OR LESS',
    'MANU/DEL:CANNABIS OVER 10 GMS':'MANUFACTURE / DELIVER - CANNABIS OVER 10 GRAMS',
    'MANU/DELIVER: HALLUCINOGEN':'MANUFACTURE / DELIVER - HALLUCINOGEN',
    'MANU/DELIVER: HEROIN (WHITE)':'MANUFACTURE / DELIVER - HEROIN (WHITE)',
    'MANU/DELIVER: HEROIN(BRN/TAN)':'MANUFACTURE / DELIVER - HEROIN (TAN / BROWN TAR)',
    'MANU/DELIVER:AMPHETAMINES':'MANUFACTURE / DELIVER - AMPHETAMINES',
    'MANU/DELIVER:BARVITUATES':'MANUFACUTRE / DELIVER - BARVITUATES',
    'MANU/DELIVER:COCAINE':'MANUFACTURE / DELIVER - COCAINE',
    'MANU/DELIVER:CRACK':'MANUFACTURE / DELIVER - CRACK',
    'MANU/DELIVER:HEROIN(BLACK TAR)':'MANUFACTURE / DELIVER - HEROIN (BLACK TAR)',
    'MANU/DELIVER:LOOK-ALIKE DRUG':'MANUFACTURE / DELIVER - LOOK-ALIKE DRUG',
    'MANU/DELIVER:PCP':'MANUFACTURE / DELIVER - PCP',
    'MANU/DELIVER:SYNTHETIC DRUGS':'MANUFACTURE / DELIVER - SYNTHETIC DRUGS',
    'BOLITA OR BOLI PUL/RUNNER':'BOLITA OR BOLI PUL / RUNNER',
    'BOLITA OR BOLI PUL/WRITER':'BOLITA OR BOLI PUL / WRITER',
    'BOOKMAKING/HORSES':'BOOKMAKING / HORSES',
    'BOOKMAKING/SPORTS':'BOOKMAKING / SPORTS',
    'ENDANGERING LIFE/HEALTH CHILD':'ENDANGERING LIFE / HEALTH OF CHILD',
    'GAME/CARDS':'GAME / CARDS',
    'GAME/DICE':'GAME / DICE',
    'GAME/AMUSEMENT DEVICE':'GAME / AMUSEMENT DEVICE',
    'INDENCENT SOLICITATION/CHILD':'INDENCENT SOLICITATION OF A CHILD',
    'INDENCENT SOLICITATION/ADULT':'INDENCENT SOLICITATION OF AN ADULT',
    'LOTTERY/OTHER':'LOTTERY / OTHER',
    'CHILD ABDUCTION/STRANGER': 'CHILD ABDUCTION / STRANGER',
    'COMMERCIAL SEX ACTS':'COMMERCIAL SEXUAL ACTS',
    'CONTRIBUTE DELINQUENCY OF A CHILD':'CONTRIBUTE TO THE DELINQUENCY OF CHILD',
    'CRIM SEX ABUSE BY FAM MEMBER':'CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
    'CYCLE, SCOOTER, BIKE W-VIN':'CYCLE, SCOOTER, BIKE WITH VIN',
    'DEFACE IDENT MARKS OF FIREARM':'DEFACE IDENTIFICATION MARKS OF FIREARM',
    'DELIVER CANNABIS TO PERSON <18':'DELIVER CANNABIS TO PERSON UNDER 18',
    'DEL CONT SUBS TO PERSON <18':'DELIVER CONTROLLED SUBSTANCES TO PERSON UNDER 18',
    'FALSE/STOLEN/ALTERED TRP':'FALSE / STOLEN / ALTERED TRP',
    'FINAN EXPLOIT-ELDERLY/DISABLED':'FINANCIAL EXPLOITATION OF AN ELDERLY OR DISABLED PERSON',
    'FINANCIAL ID THEFT: OVER $300':'FINANCIAL IDENTITY THEFT OVER $300',
    'FINANCIAL ID THEFT:$300 &UNDER':'FINANCIAL IDENTITY THEFT $300 AND UNDER',
    'FINANCIAL IDENTITY THEFT: OVER $300':'FINANCIAL IDENTITY THEFT OVER $300',
    'FINANCIAL IDENTITY THEFT: $300 & UNDER':'FINANCIAL IDENTITY THEFT $300 AND UNDER',
    'AGG CRIM SEX ABUSE FAM MEMBER':'AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
    'AGG CRIMINAL SEXUAL ABUSE':'AGGRAVATED CRIMINAL SEXUAL ABUSE',
    'AGG PO HANDS NO/MIN INJURY':'AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET, NO INJURY',
    'AGG PRO.EMP: HANDGUN':'AGGRAVATED PROTECTED EMPLOYEE - HANDGUN',
    'AGG PRO.EMP: OTHER DANG WEAPON':'AGGRAVATED PROTECTED EMPLOYEE - OTHER DANGEROUS WEAPON',
    'AGG PRO.EMP:KNIFE/CUTTING INST':'AGGRAVATED PROTECTED EMPLOYEE - KNIFE / CUTTING INSTRUMENT',
    'AGG RITUAL MUT:HANDGUN':'AGGRAVATED RITUAL MUT:HANDGUN',
    'AGG RITUAL MUT:KNIFE/CUTTING I':'AGGRAVATED RITUAL MUT : KNIFE / CUTTING',
    'AGG RITUAL MUT:OTH DANG WEAPON':'AGGRAVATED RITUAL MUT : OTHER DANGEROUS WEAPON',
    'AGG SEX ASSLT OF CHILD FAM MBR':'AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
    'AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY':'AGGRAVATED DOMESTIC BATTERY - HANDS / FISTS / FEET SERIOUS INJURY',
    'AGGRAVATED DOMESTIC BATTERY: HANDS/FISTS/FEET SERIOUS INJURY':'AGGRAVATED DOMESTIC BATTERY - HANDS / FISTS / FEET SERIOUS INJURY',
    'AGG. PROTECTED EMPLOYEE - HANDS, FISTS, FEET, SERIOUS INJURY':'AGGRAVATED PROTECTED EMPLOYEE - HANDS, FISTS, FEET, SERIOUS INJURY',
    'AGG: FINANCIAL ID THEFT':'AGGRAVATED FINANCIAL IDENTITY THEFT',
    'AGG: HANDS/FIST/FEET NO/MINOR INJURY':'AGGRAVATED - HANDS, FISTS, FEET, NO / MINOR INJURY',
    'AGGRAVATED: HANDGUN':'AGGRAVATED - HANDGUN',
    'AGGRAVATED: KNIFE/CUT INSTR':'AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
    'AGGRAVATED:KNIFE/CUT INSTR':'AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
    'AGGRAVATED: OTHER':'AGGRAVATED - OTHER',
    'AGGRAVATED: OTHER DANG WEAPON':'AGGRAVATED - OTHER DANGEROUS WEAPON',
    'AGGRAVATED: OTHER FIREARM':'AGGRAVATED - OTHER FIREARM',
    'AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST':'AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT',
    'AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON':'AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON',
    'AGGRAVATED DOMESTIC BATTERY: OTHER FIREARM':'AGGRAVATED DOMESTIC BATTERY - OTHER FIREARM',
    'AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY':'AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET, NO INJURY',
    'AGGRAVATED P.O. - HANDS, FISTS, FEET, SERIOUS INJURY':'AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET, SERIOUS INJURY',
    'AGGRAVATED PO: HANDGUN':'AGGRAVATED POLICE OFFICER - HANDGUN',
    'AGGRAVATED PO: KNIFE/CUT INSTR':'AGGRAVATED POLICE OFFICER - KNIFE / CUTTING INSTRUMENT',
    'AGGRAVATED PO: OTHER DANG WEAP': 'AGGRAVATED POLICE OFFICER - OTHER DANGEROUS WEAPON',
    'AGGRAVATED PO: OTHER FIREARM':'AGGRAVATED POLICE OFFICER - OTHER FIREARM',
    'AGGRAVATED PO:KNIFE/CUT INSTR':'AGGRAVATED POLICE OFFICER - KNIFE / CUTTING INSTRUMENT',
    'AGGRAVATED: KNIFE/CUTTING INSTR':'AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
    'ALTER/FORGE PRESCRIPTION':'ALTER / FORGE PRESCRIPTION',
    'ARMED:KNIFE/CUTTING INSTRUMENT':'ARMED - KNIFE / CUTTING INSTRUMENT',
    'ARMED: OTHER DANGEROUS WEAPON':'ARMED - OTHER DANGEROUS WEAPON',
    'ARMED: OTHER FIREARM':'ARMED - OTHER FIREARM',
    'ARMED: HANDGUN':'ARMED - HANDGUN',
    'ATT AGG CRIM SEXUAL ABUSE':'ATTEMPT AGGRAVATED CRIMINAL SEXUAL ABUSE',
    'ATT AGG CRIMINAL SEXUAL ABUSE':'ATTEMPT AGGRAVATED CRIMINAL SEXUAL ABUSE',
    'ATT CRIM SEXUAL ABUSE':'ATTEMPT CRIMINAL SEXUAL ABUSE',
    'ATT: AUTOMOBILE':'ATTEMPT - AUTOMOBILE',
    'ATT: TRUCK, BUS, MOTOR HOME':'ATTEMPT - TRUCK, BUS, MOTOR HOME',
    'ATTEMPT: CYCLE, SCOOTER, BIKE W-VIN':'ATTEMPT - CYCLE, SCOOTER, BIKE WITH VIN',
    'ATTEMPT AGG: HANDGUN':'ATTEMPT AGGRAVATED - HANDGUN',
    'ATTEMPT AGG: KNIFE/CUT INSTR':'ATTEMPT AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
    'ATTEMPT AGG: OTHER':'ATTEMPT AGGRAVATED - OTHER',
    'ATTEMPT AGG: OTHER DANG WEAPON':'ATTEMPT AGGRAVATED - OTHER DANGEROUS WEAPON',
    'ATTEMPT: AGGRAVATED':'ATTEMPT AGGRAVATED',
    'ATTEMPT: ARMED-HANDGUN':'ATTEMPT ARMED - HANDGUN',
    'ATTEMPT: ARMED-KNIFE/CUT INSTR':'ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT',
    'ATTEMPT: ARMED-OTHER DANG WEAP':'ATTEMPT ARMED - OTHER DANGEROUS WEAPON',
    'ATTEMPT: ARMED-OTHER FIREARM':'ATTEMPT ARMED - OTHER FIREARM',
    'ATTEMPT: STRONGARM-NO WEAPON':'ATTEMPT STRONG ARM - NO WEAPON',
}

# Apply the replacement
df['Description'] = df['Description'].apply(lambda x: replace_description.get(x, x))
df.head(20)

,ID,Case Number,Date Time,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:00,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,49.0,1.0,8,NaN,NaN,2007,2015-08-17 15:03:00,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,36.0,19.0,1,1141387.0,1913179.0,2021,2023-11-18 15:39:00,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,50.0,13.0,1,1152781.0,1941458.0,2021,2023-11-18 15:39:00,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:00,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET...",SMALL RETAIL STORE,True,False,632,6,6.0,44.0,8,1183071.0,1847869.0,2023,2023-12-09 15:41:00,41.737751,-87.604856,"(41.737750767, -87.604855911)"
5,1930689,HH109118,2002-01-05 21:24:00,007XX E 103 ST,820,THEFT,$500 AND UNDER,GAS STATION,True,False,512,5,NaN,NaN,6,NaN,NaN,2002,2016-02-04 06:33:00,NaN,NaN,NaN
6,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,122,1,42.0,32.0,14,1174694.0,1901831.0,2023,2023-11-04 15:40:00,41.886018,-87.633938,"(41.886018055, -87.633937881)"
7,13210088,JG423627,2023-08-31 12:00:00,023XX W JACKSON BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,1225,12,27.0,28.0,11,1160870.0,1898642.0,2023,2023-09-16 15:41:00,41.877565,-87.684791,"(41.877565108, -87.68479102)"
8,13210004,JG422532,2023-07-24 21:45:00,073XX S JEFFERY BLVD,281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,333,3,7.0,43.0,2,1190812.0,1856743.0,2023,2023-09-16 15:41:00,41.761919,-87.576209,"(41.7619185, -87.576209245)"
9,13210062,JG423596,2023-08-27 07:00:00,034XX N LAWNDALE AVE,820,THEFT,$500 AND UNDER,APARTMENT,False,False,1732,17,30.0,21.0,6,1151117.0,1922554.0,2023,2023-09-16 15:41:00,41.943379,-87.719974,"(41.943378528, -87.7199738)"
10,13210107,JG411849,2023-09-04 21:30:00,053XX S HOMAN AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE - GARAGE,False,False,822,8,14.0,63.0,14,1154617.0,1869046.0,2023,2023-09-16 15:41:00,41.796477,-87.708541,"(41.796477414, -87.708540915)"
11,13210060,JG423567,2023-08-15 14:20:00,077XX S SPAULDING AVE,810,THEFT,OVER $500,RESIDENCE - PORCH / HALLWAY,False,False,835,8,18.0,70.0,6,1155724.0,1853097.0,2023,2023-09-16 15:41:00,41.752689,-87.704909,"(41.752688801, -87.704908791)"
12,13210120,JG423499,2023-07-24 16:09:00,002XX W 75TH ST,1120,DECEPTIVE PRACTICE,FORGERY,CURRENCY EXCHANGE,False,False,731,7,6.0,69.0,10,1175716.0,1855233.0,2023,2023-09-16 15:41:00,41.758126,-87.631583,"(41.758126171, -87.631582508)"
13,13210071,JG421086,2023-09-03 10:27:00,089XX S LOOMIS ST,890,THEFT,FROM BUILDING,APARTMENT,False,False,2222,22,21.0,73.0,6,1168564.0,1845472.0,2023,2023-09-16 15:41:00,41.731498,-87.658075,"(41.731497731, -87.658074565)"
14,13210035,JG422370,2023-08-17 07:00:00,019XX W 71ST ST,820,THEFT,$500 AND UNDER,STREET,False,False,735,7,17.0,67.0,6,1164749.0,1857588.0,2023,2023-09-16 15:41:00,41.764827,-87.671709,"(41.764827083, -87.671709119)"
15,13210008,JG422517,2023-08-24 14:27:00,031XX S WALLACE ST,1110,DECEPTIVE PRACTICE,BOGUS CHECK,CURRENCY EXCHANGE,False,False,915,9,11.0,60.0,11,1172803.0,1884190.0,2023,2023-09-16 15:41:00,41.837652,-87.641404,"(41.837651929, -87.641404086)"
16,13210072,JG422242,2023-08-11 11:00:00,0000X S ALBANY AVE,1790,OFFENSE INVOLVING CHILDREN,CHILD ABDUCTION,RESIDENCE,False,True,1124,11,28.0,27.0,26,1155914.0,1899709.0,2023,2023-09-16 15:41:00,41.880594,-87.702959,"(41.880594385, -87.702959421)"
17,13278080,JG500620,2023-11-11 00:00:00,038XX W MADISON ST,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1122,11,28.0,26.0,7,1150898.0,1899740.0,2023,2023-11-18 15:40:00,41.880779,-87.721377,"(41.880779076, -87.721377025)"
18,13272487,JG498648,2023-11-10 05:30:00,019XX N AUSTIN AVE,810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,2513,25,29.0,25.0,6,1136098.0,1912178.0,2023,2023-11-18 15:40:00,41.915187,-87.775425,"(41.915187259, -87.775425225)"
19,13279067,JG506481,2023-11-03 12:00:00,006XX W GRACE ST,1156,DECEPTIVE PRACTICE,ATTEMPT - FINANCIAL IDENTITY THEFT,APARTMENT,False,False,1925,19,46.0,6.0,11,1171140.0,1925861.0,2023,2023-11-18 15:39:00,41.952036,-87.646282,"(41.952036311, -87.646281883)"

In [ ]:
# Replacement dictionary
replace_loc_des ={
    'BONT/WATERCRAFT':'BONT / WATERCRAFT',
    'CHA HALLWAY/STAIRWELL/ELEVATOR':'CHA HALLWAY / STAIRWELL / ELEVATOR',
    'CHA PARKING LOT/GROUNDS':'CHA PARKING LOT / GROUNDS',
    'CHURCH/SYNAGOGUE/PLACE OF WORKSHIP':'CHURCH / SYNAGOGUE / PLACE OF WORKSHIP',
    'CLEARNERS/LAUNDROMAT':'CLEARNERS / LAUNDROMAT',
    'COLLEGE/UNIVERSITY GROUNDS':'COLLEGE / UNIVERSITY - GROUNDS',
    'COLLEGE/UNIVERSITY RESIDENCE HALL':'COLLEGE / UNIVERSITY - RESIDENCE HALL',
    'FACTORY/MANUFACTURING BUILDING':'FACTORY / MANUFACTURING BUILDING',
    'GAS STATION DRIVER/PROP.':'GAS STATION DRIVER / PROPERTY',
    'GOVERNMENT BUILDING/PROPERTY':'GOVERNMENT BUILDING / PROPERTY',
    'HIGHWAY/EXPRESSWAY':'HIGHWAY / EXPRESSWAY',
    'HOSPITAL BUILDING/GROUNDS':'HOSPITAL BUILDING / GROUNDS',
    'HOTEL/MOTEL':'HOTEL / MOTEL',
    'LAKEFRONT/WATERFRONT/RIVERBANK':'LAKEFRONT / WATERFRONT / RIVERBANK',
    'MEDICAL/DENTAL OFFICE':'MEDICAL / DENTAL OFFICE',
    'MOVIE HOUSE/THEATER':'MOVIE HOUSE / THEATER',
    'NURSING HOME/RETIREMENT HOME':'NURSING HOME / RETIREMENT HOME',
    'OTHER RAILROAD PROP / TRAIN DEPOT':'OTHER RAILROAD PROPERTY / TRAIN DEPOT',
    'PARKING LOT/GARAGE(NON.RESID.)':'PARKING LOT / GARAGE (NON RESIDENTIAL)',
    'POLICE FACILITY/VEH PARKING LOT':'POLICE FACILITY / VEHICLE PARKING LOT',
    'POOLROOM':'POOL ROOM',
    'RESIDENCE-GARAGE':'RESIDENCE - GARAGE',
    'RESIDENCE PORCH/HALLWAY':'RESIDENCE - PORCH / HALLWAY',
    'RESIDENCIAL YARD (FRONT/BACK)':'RESIDENCE - YARD (FRONT / BACK)',
    'TAXICAB':'TAXI CAB',
    'TAVERN/LIQUOR STORE':'TAVERN / LIQUOR STORE',
    'VACANT LOT/LAND':'VANCANT LOT / LAND',
    'VEHICLE-COMMERCIAL':'VEHICLE - COMMERCIAL',
    'SPORTS ARENA/STADIUM':'SPORTS ARENA / STADIUM',
    'SCHOOL, PRIVATE, BUILDINGS':'SCHOOL - PRIVATE BUILDINGS',
    'SCHOOL, PRIVATE, GROUNDS':'SCHOOL - PRIVATE GROUNDS',
    'SCHOOL, PUBLIC, BUILDINGS':'SCHOOL - PUBLIC BUILDINGS',
    'SCHOOL, PUBLIC, GROUNDS':'SCHOOL - PUBLIC GROUNDS'
}

# Apply the replacement
df['Location Description'] = df['Location Description'].apply(lambda x: replace_loc_des.get(x, x))
df.head(20)

,ID,Case Number,Date Time,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:00,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,49.0,1.0,8,NaN,NaN,2007,2015-08-17 15:03:00,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,36.0,19.0,1,1141387.0,1913179.0,2021,2023-11-18 15:39:00,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,50.0,13.0,1,1152781.0,1941458.0,2021,2023-11-18 15:39:00,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:00,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET...",SMALL RETAIL STORE,True,False,632,6,6.0,44.0,8,1183071.0,1847869.0,2023,2023-12-09 15:41:00,41.737751,-87.604856,"(41.737750767, -87.604855911)"
5,1930689,HH109118,2002-01-05 21:24:00,007XX E 103 ST,820,THEFT,$500 AND UNDER,GAS STATION,True,False,512,5,NaN,NaN,6,NaN,NaN,2002,2016-02-04 06:33:00,NaN,NaN,NaN
6,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,122,1,42.0,32.0,14,1174694.0,1901831.0,2023,2023-11-04 15:40:00,41.886018,-87.633938,"(41.886018055, -87.633937881)"
7,13210088,JG423627,2023-08-31 12:00:00,023XX W JACKSON BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,1225,12,27.0,28.0,11,1160870.0,1898642.0,2023,2023-09-16 15:41:00,41.877565,-87.684791,"(41.877565108, -87.68479102)"
8,13210004,JG422532,2023-07-24 21:45:00,073XX S JEFFERY BLVD,281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,333,3,7.0,43.0,2,1190812.0,1856743.0,2023,2023-09-16 15:41:00,41.761919,-87.576209,"(41.7619185, -87.576209245)"
9,13210062,JG423596,2023-08-27 07:00:00,034XX N LAWNDALE AVE,820,THEFT,$500 AND UNDER,APARTMENT,False,False,1732,17,30.0,21.0,6,1151117.0,1922554.0,2023,2023-09-16 15:41:00,41.943379,-87.719974,"(41.943378528, -87.7199738)"
10,13210107,JG411849,2023-09-04 21:30:00,053XX S HOMAN AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE - GARAGE,False,False,822,8,14.0,63.0,14,1154617.0,1869046.0,2023,2023-09-16 15:41:00,41.796477,-87.708541,"(41.796477414, -87.708540915)"
11,13210060,JG423567,2023-08-15 14:20:00,077XX S SPAULDING AVE,810,THEFT,OVER $500,RESIDENCE - PORCH / HALLWAY,False,False,835,8,18.0,70.0,6,1155724.0,1853097.0,2023,2023-09-16 15:41:00,41.752689,-87.704909,"(41.752688801, -87.704908791)"
12,13210120,JG423499,2023-07-24 16:09:00,002XX W 75TH ST,1120,DECEPTIVE PRACTICE,FORGERY,CURRENCY EXCHANGE,False,False,731,7,6.0,69.0,10,1175716.0,1855233.0,2023,2023-09-16 15:41:00,41.758126,-87.631583,"(41.758126171, -87.631582508)"
13,13210071,JG421086,2023-09-03 10:27:00,089XX S LOOMIS ST,890,THEFT,FROM BUILDING,APARTMENT,False,False,2222,22,21.0,73.0,6,1168564.0,1845472.0,2023,2023-09-16 15:41:00,41.731498,-87.658075,"(41.731497731, -87.658074565)"
14,13210035,JG422370,2023-08-17 07:00:00,019XX W 71ST ST,820,THEFT,$500 AND UNDER,STREET,False,False,735,7,17.0,67.0,6,1164749.0,1857588.0,2023,2023-09-16 15:41:00,41.764827,-87.671709,"(41.764827083, -87.671709119)"
15,13210008,JG422517,2023-08-24 14:27:00,031XX S WALLACE ST,1110,DECEPTIVE PRACTICE,BOGUS CHECK,CURRENCY EXCHANGE,False,False,915,9,11.0,60.0,11,1172803.0,1884190.0,2023,2023-09-16 15:41:00,41.837652,-87.641404,"(41.837651929, -87.641404086)"
16,13210072,JG422242,2023-08-11 11:00:00,0000X S ALBANY AVE,1790,OFFENSE INVOLVING CHILDREN,CHILD ABDUCTION,RESIDENCE,False,True,1124,11,28.0,27.0,26,1155914.0,1899709.0,2023,2023-09-16 15:41:00,41.880594,-87.702959,"(41.880594385, -87.702959421)"
17,13278080,JG500620,2023-11-11 00:00:00,038XX W MADISON ST,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1122,11,28.0,26.0,7,1150898.0,1899740.0,2023,2023-11-18 15:40:00,41.880779,-87.721377,"(41.880779076, -87.721377025)"
18,13272487,JG498648,2023-11-10 05:30:00,019XX N AUSTIN AVE,810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,2513,25,29.0,25.0,6,1136098.0,1912178.0,2023,2023-11-18 15:40:00,41.915187,-87.775425,"(41.915187259, -87.775425225)"
19,13279067,JG506481,2023-11-03 12:00:00,006XX W GRACE ST,1156,DECEPTIVE PRACTICE,ATTEMPT - FINANCIAL IDENTITY THEFT,APARTMENT,False,False,1925,19,46.0,6.0,11,1171140.0,1925861.0,2023,2023-11-18 15:39:00,41.952036,-87.646282,"(41.952036311, -87.646281883)"

In [ ]:
# Fill NaN values with the mode (most frequent value)
df['Location Description'] = df['Location Description'].fillna(df['Location Description'].mode()[0])
df['Location Description'].head(20)

0                                      OTHER
1                                     STREET
2                                PARKING LOT
3                                  APARTMENT
4                         SMALL RETAIL STORE
5                                GAS STATION
6     PARKING LOT / GARAGE (NON RESIDENTIAL)
7                                     STREET
8                                  APARTMENT
9                                  APARTMENT
10                        RESIDENCE - GARAGE
11               RESIDENCE - PORCH / HALLWAY
12                         CURRENCY EXCHANGE
13                                 APARTMENT
14                                    STREET
15                         CURRENCY EXCHANGE
16                                 RESIDENCE
17                                    STREET
18    PARKING LOT / GARAGE (NON RESIDENTIAL)
19                                 APARTMENT
Name: Location Description, dtype: object

In [ ]:
df.isnull().sum() # Again check Null Values

ID                           0
Case Number                  0
Date Time                    0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description         0
Arrest                       0
Domestic                     0
Beat                         0
District                     0
Ward                    336325
Community Area          334906
FBI Code                     0
X Coordinate              6912
Y Coordinate              6912
Year                         0
Updated On                   0
Latitude                  6912
Longitude                 6912
Location                  6912
dtype: int64

In [ ]:
print(df['Ward'].isnull().mean() * 100) # Check the percentage of Null values in 'Ward' Column

61.150111182020325

In [ ]:
print(df['Community Area'].isnull().mean() * 100) # Check the percentage of Null Values in 'Community Area' Column

60.89211071292857

In [ ]:
# Check the percentage of Null Values in 'X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude' and 'Location' Columns
print(df[['X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude', 'Location']].isnull().mean() * 100)

X Coordinate    1.25673
Y Coordinate    1.25673
Latitude        1.25673
Longitude       1.25673
Location        1.25673
dtype: float64

In [ ]:
# Check the percentage of Null Values in 'X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude' and 'Location' Columns
print(df[['X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude', 'Location']].isnull().mean() * 100)

X Coordinate    1.25673
Y Coordinate    1.25673
Latitude        1.25673
Longitude       1.25673
Location        1.25673
dtype: float64

In [ ]:
# Fill NaN values in 'Ward' by District using the mode of each district
df['Ward'] = df.groupby('District')['Ward'].transform(lambda x: x.fillna(x.mode()[0]))

# Fill NaN values in 'Community Area' by District using the mode of each district
df['Community Area'] = df.groupby('District')['Community Area'].transform(lambda x: x.fillna(x.mode()[0]))

In [ ]:
df.isnull().sum() # Check null values again

ID                         0
Case Number                0
Date Time                  0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description       0
Arrest                     0
Domestic                   0
Beat                       0
District                   0
Ward                       0
Community Area             0
FBI Code                   0
X Coordinate            6912
Y Coordinate            6912
Year                       0
Updated On                 0
Latitude                6912
Longitude               6912
Location                6912
dtype: int64

In [ ]:
df.dropna(inplace=True) # Drop rows with NaN values in any column in place

In [ ]:
df.isnull().sum() # Check null values again

ID                      0
Case Number             0
Date Time               0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [ ]:
df.shape # Check the Shape of the file

(543087, 22)

In [ ]:
# Sort by 'ID' in ascending order
df.sort_values(by='ID', ascending=True, inplace=True)
df.head()

,ID,Case Number,Date Time,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
204687,634,G000705,2001-01-01 10:40:00,024XX W MONROE ST,110,HOMICIDE,FIRST DEGREE MURDER,CHA STAIRWELL,False,False,1125,11,2.0,28.0,1,1159921.0,1899604.0,2001,2022-09-01 15:42:00,41.880225,-87.688249,"(41.880224549, -87.688248952)"
234885,635,F803142,2001-01-01 15:10:00,023XX N MILWAUKEE AVE,110,HOMICIDE,FIRST DEGREE MURDER,AUTO,False,False,1414,14,35.0,22.0,1,1156620.0,1915710.0,2001,2022-09-19 15:41:00,41.924488,-87.699933,"(41.924488265, -87.699933231)"
262945,636,G008548,2001-01-04 22:30:00,035XX W 12 PL,110,HOMICIDE,FIRST DEGREE MURDER,BASEMENT,True,False,1021,10,24.0,29.0,1,1153021.0,1894062.0,2001,2022-09-19 15:41:00,41.865156,-87.713732,"(41.865156224, -87.71373199)"
103154,637,G005960,2001-01-06 10:35:00,014XX N HARDING ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2535,25,31.0,19.0,1,0.0,0.0,2001,2024-01-28 15:40:00,36.619446,-91.686566,"(36.619446395, -91.686565684)"
328575,638,G008793,2001-01-05 16:22:00,016XX W 80 ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,611,6,17.0,44.0,1,1166640.0,1851658.0,2001,2023-05-04 15:40:00,41.748514,-87.664947,"(41.748514222, -87.664946923)"

In [ ]:
# Save the DataFrame to a CSV file
df.to_csv('Cleaned Crime_Data.csv', index=False)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df1 = pd.read_csv('Cleaned Crime_Data.csv')

In [ ]:
df.isnull().sum()

ID                      0
Case Number             0
Date Time               0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Database connection parameters
server = 'localhost'    # SQL Server host
database = 'Chicago'    # Database name
username = 'root'         # SQL Server username (default admin user is usually 'sa')
password = '1234'       # Your password

# Create the SQLAlchemy engine for SQL Server
engine = create_engine(
    f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server"
)

# Read the CSV file
data = pd.read_csv('Cleaned Crime_Data.csv')

# Rename columns to match the SQL Server table schema
data.columns = [
    "ID",
    "Case_Number",
    "date_time",
    "Block",
    "IUCR",
    "Primary_Type",
    "Description",
    "Location_Description",
    "Arrest",
    "Domestic",
    "Beat",
    "District",
    "Ward",
    "Community_area",
    "FBI_Code",
    "X_Coordinate",
    "Y_Coordinate",
    "Year",
    "updated_on",
    "Latitude",
    "Longitude",
    "Location"
]

# Ensure datetime columns match SQL Server's datetime format
data["date_time"] = pd.to_datetime(data["date_time"], errors='coerce')
data["updated_on"] = pd.to_datetime(data["updated_on"], errors='coerce')

# Insert data into the 'crime_data' table in SQL Server
data.to_sql('crime_data', con=engine, if_exists='append', index=False, chunksize=10000)

print("Data inserted successfully.")

ModuleNotFoundError: No module named 'pyodbc'